# Site settings
title: David Johnson
email: david.j.c.johnson@gmail.com
url: https://daaavid.github.io
description: "Mobile Dev David Johnson's portfolio site."
skills: "Mobile Developer"
languages: "Swift - Objective C"
meta_author: David Johnson

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3faeb2 #18bc9c #80B3FF
  primary-rgb: "25, 68, 70" #"24,288,156" #"128,179,255"
  secondary: 353530 #2c3e50 #FD6E8A
  secondary-dark: 252521 #233140 #A2122F

# Footer settings
footer:
  copyright: David Johnson
  contactHeader: Contact
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/daaavid_johnson
  - title: github
    url: http://github.com/daaavid
  - title: linkedin
    url: https://www.linkedin.com/in/david-johnson-8b4783a7

# Contact details
contactDetails:
  - line: David Johnson
  - line: david.j.c.johnson@gmail.com
  - line: 920.285.6700
  - line:
  - line: Orlando, FL
  - line:
  - line: <img src="http://api.qrserver.com/v1/create-qr-code/?color=000000&amp;bgcolor=FFFFFF&amp;data=BEGIN%3AVCARD%0AVERSION%3A2.1%0AFN%3ADavid+Johnson%0AN%3AJohnson%3BDavid%0ATEL%3BCELL%3A920-285-6700%0AEMAIL%3BHOME%3BINTERNET%3Adavid.j.c.johnson%40gmail.com%0AEND%3AVCARD%0A&amp;qzone=1&amp;margin=0&amp;size=400x400&amp;ecc=L" alt="qr code" / width="120" height="120">

aboutMeLanguages:
  - line: Swift
  - line: Objective C
  - line: HTML and CSS (learned it just to make this website!)

aboutMeTools:
  - line: Xcode
  - line: Github
  # - line: CocoaPods
  - line: Atom
  - line: Jekyll
  - line: Bootstrap

aboutMeIAm:
  - line: Passionate about programming and development
  - line: Eager to take on new challenges
  - line: Determined and self-motivated

# Postal address (add as many lines as necessary)
#  address:
#    - line: David Johnson
#    - line: david.j.c.johnson@gmail.com
#    - line: (920) 285-6700
#    - line:
#    - line: Orlando, FL

# Credits content
credits: 'This site was based on Freelancer: a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
