# Site settings
title: *David Johnson
email: david.j.c.johnson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  David Johnson's github page.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: daaavid_johnson
github_username:  daaavid
theme_color: "$blue"

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  journal:
    output: true
    permalink: /journal/:path/
