# Site settings
title: David J
email: david@bronze5.net
url: https://portfolio.bronze5.net
description: "David J's Dev Site."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffffff'
  links: '#219ab3'

# Footer settings
footer: David J

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/daaavid_johnson
  - title: github
    url: https://github.com/daaavid
  - title: linkedin
    url: https://www.linkedin.com/in/daaavid

contactDetails:
  - line: David Johnson
  - line: <a href="mailto:david@bronze5.net" target="_top">david@bronze5.net</a>
  - line: 920.285.6700
  - line:
  - line: Orlando, FL
  - line:
  - line: <img src="http://api.qrserver.com/v1/create-qr-code/?color=000000&amp;bgcolor=FFFFFF&amp;data=BEGIN%3AVCARD%0AVERSION%3A2.1%0AFN%3ADavid+Johnson%0AN%3AJohnson%3BDavid%0ATEL%3BCELL%3A920-285-6700%0AEMAIL%3BHOME%3BINTERNET%3Adavid%40bronze5.net%0AEND%3AVCARD%0A&amp;qzone=1&amp;margin=0&amp;size=400x400&amp;ecc=L" alt="qr code" / width="120" height="120">

aboutMeLanguages:
  - line: Swift
  - line: Objective C
  - line: HTML
  - line: CSS

aboutMeTools:
  - line: Xcode
  # - line: CocoaPods
  - line: Atom
  - line: Github
  - line: Jekyll
  - line: Photoshop



aboutMeIAm:
  - line: Passionate about programming and development
  - line: Eager to take on new challenges
  - line: Determined and self-motivated


# Build settings
markdown: kramdown
permalink: pretty
